### ISSUE TITLE
Per-App Authorisation

### ISSUE THREAD

**Issue by stupidpupil** [stupidpupil/rumba#1]
Use IIS URL Authorisation and sub-directory configuration to setup and teardown per-app authorisation.

## Example rumba.yml
``` yaml

allowlist-users:
  - some_username

allowlist-groups:
  - A Group

```

## References

[Understanding IIS 7.0 URL Authorization](https://docs.microsoft.com/en-us/iis/manage/configuring-security/understanding-iis-url-authorization)
